%% Script to compute the PSD mean of trials.

%This script calculate the PSD mean of the trials of each EEG recording. It
%generates a xls file with the area of the PSD function under the 5
%frequency bands that are found in the cortex activity (alpha, beta, theta,
%delata an gamma), although gamma will have no values bc of the bandpass
%filter used in the previous scripts. IT has to be ran in a directory with
%all the xls files with the trials (generated by the trials.m file).
%MATLAB version: 2021b
%Develop by Daniel Jimeno in the FENNSI group at National Hospital of
%Paraplegics of Toledo, Spain

% absolute route to where the trial files should be
route = "C:\\Users\\lacar\\Desktop\\sujeto_10\\asr\\";
% Sampling Frequency
Fs = 256;   
f=0:0.5:128;
real_freq=f(5:58);
% Nyquist Frequency
Fn = Fs/2; 
resolution=0.5;
noverlap=0;
nfft=round(Fs/resolution);
window=hanning(nfft);
L = 1200;
% passband
Fpass = [0.5 40]; 
        
%We write in a file all the xls data files and in other file the events
%files so we can go extracting data for each file in the following loop
left_read=dir(strcat(pwd,'/*_LEFT.xls'));
left_name=char(left_read.name);
right_read=dir(strcat(pwd,'/*_RIGHT.xls'));
right_name=char(right_read.name);


for d=1:length(left_name(:,1))
    kl=strfind(left_name(d,:),".");
    name_data=left_name(d,1:kl-13);
    record_day=d;
    %eeg band names to write the tables to store the data
    freq_names=["alpha" "alpha peak" "low beta" "high beta" "beta" "gamma" "theta"];
    
   %load the data from the trials
    if exist(route+name_data+"_trials\\"+name_data+"_trials_LEFT.xls")==2
        [datos_pre_left,channels_pre_left] = xlsread(route+"trial\\"+name_data+"_trials_LEFT.xls","pre_trials_PSD");
        [datos_pre_right,channels_pre_right] = xlsread(route+"trial\\"+name_data+"_trials_RIGHT.xls","pre_trials_PSD");
        [datos_post_left,channels_post_left] = xlsread(route+"trial\\"+name_data+"_trials_LEFT.xls","post_trials_PSD");
        [datos_post_right,channels_post_right] = xlsread(route+"trial\\"+name_data+"_trials_RIGHT.xls","post_trials_PSD");
        if isnan(datos_post_right(end,1))
            vas=datos_post_right(end,2);
        end
        datos_post_right=datos_post_right(1:end-1,:); %data from right trials
        datos_post_left=datos_post_left(1:end-1,:); %data from left trials
        channels_pre_left=channels_pre_left(1,:); %names of channels in right trials
        channels_post_left=channels_post_left(1,:); %name of channels in left trials
        channels_pre_right=channels_pre_right(1,:); %warnings from right trials
        channels_post_right=channels_post_right(1,:); % warnigs from left trials
    end
    
    %empty arrays to store the data generated
    mean_left_pre=[];
    mean_left_post=[];
    mean_right_pre=[];
    mean_right_post=[];
    mean_names=[];
    power_right_pre=[];
    power_right_post=[];
    power_left_pre=[];
    power_left_post=[];

    %% MEAN OF PSD TRIALS

    %compute the mean of the PSD of trials of each channels. We focus on the
    %central channels (C3, Cz, C4)
    
    %RIGHT
    %C3 RIGHT
    cell_right_c3=strfind(channels_pre_right,'C3');
    c3_positions_right=[];
    for i=1:length(cell_right_c3)
        if cell2mat(cell_right_c3(i))==1
            c3_positions_right=[c3_positions_right i];
        end
    end
    
    if isempty(c3_positions_right)==0
        mean_right_c3_pre=mean(datos_pre_right(5:58,c3_positions_right)', 'omitnan')';
        mean_right_c3_post=mean(datos_post_right(5:58,c3_positions_right)', 'omitnan')';
        mean_right_pre=[mean_right_pre mean_right_c3_pre];
        mean_right_post=[mean_right_post mean_right_c3_post];
        mean_names=[mean_names "C3"];
        powerpre=trapz(mean_right_c3_pre(:,1));
        power_right_pre=[power_right_pre powerpre];
        powerpost=trapz(mean_right_c3_post(:,1));
        power_right_post=[power_right_post powerpost];
    end
    
    
    
    %Cz RIGHT
    cell_right_cz=strfind(channels_pre_right,'Cz');
    cz_positions_right=[];
    for i=1:length(cell_right_cz)
        if cell2mat(cell_right_cz(i))==1
            cz_positions_right=[cz_positions_right i];
        end
    end
    
    if isempty(cz_positions_right)==0
        mean_right_cz_pre=mean(datos_pre_right(5:58,cz_positions_right)', 'omitnan')';
        mean_right_cz_post=mean(datos_post_right(5:58,cz_positions_right)', 'omitnan')';
        mean_right_pre=[mean_right_pre mean_right_cz_pre];
        mean_right_post=[mean_right_post mean_right_cz_post];
        mean_names=[mean_names "CZ"];
        powerpre=trapz(mean_right_cz_pre(:,1));
        power_right_pre=[power_right_pre powerpre];
        powerpost=trapz(mean_right_cz_post(:,1));
        power_right_post=[power_right_post powerpost];
    end
    
    %C4 RIGHT
    cell_right_c4=strfind(channels_pre_right,'C4');
    c4_positions_right=[];
    for i=1:length(cell_right_c4)
        if cell2mat(cell_right_c4(i))==1
            c4_positions_right=[c4_positions_right i];
        end
    end
    
    if isempty(c4_positions_right)==0
        mean_right_c4_pre=mean(datos_pre_right(5:58,c4_positions_right)', 'omitnan')';
        mean_right_c4_post=mean(datos_post_right(5:58,c4_positions_right)', 'omitnan')';
        mean_right_pre=[mean_right_pre mean_right_c4_pre];
        mean_right_post=[mean_right_post mean_right_c4_post];
        mean_names=[mean_names "C4"];
        powerpre=trapz(mean_right_c4_pre(:,1));
        power_right_pre=[power_right_pre powerpre];
        powerpost=trapz(mean_right_c4_post(:,1));
        power_right_post=[power_right_post powerpost];
    end
    
    %LEFT%
    %C3 LEFT
    cell_left_c3=strfind(channels_pre_left,'C3');
    c3_positions_left=[];
    for i=1:length(cell_left_c3)
        if cell2mat(cell_left_c3(i))==1
            c3_positions_left=[c3_positions_left i];
        end
    end
    
    if isempty(c3_positions_left)==0
        mean_left_c3_pre=mean(datos_pre_left(5:58,c3_positions_left)', 'omitnan')';
        mean_left_c3_post=mean(datos_post_left(5:58,c3_positions_left)', 'omitnan')';
        mean_left_pre=[mean_left_pre mean_left_c3_pre];
        mean_left_post=[mean_left_post mean_left_c3_post];
        powerpre=trapz(mean_left_c3_pre(:,1));
        power_left_pre=[power_left_pre powerpre];
        powerpost=trapz(mean_left_c3_post(:,1));
        power_left_post=[power_left_post powerpost];
    end
    %Cz LEFT
    cell_left_cz=strfind(channels_pre_left,'Cz');
    cz_positions_left=[];
    for i=1:length(cell_left_cz)
        if cell2mat(cell_left_cz(i))==1
            cz_positions_left=[cz_positions_left i];
        end
    end
    if isempty(cz_positions_left)==0
        mean_left_cz_pre=mean(datos_pre_left(5:58,cz_positions_left)', 'omitnan')';
        mean_left_cz_post=mean(datos_post_left(5:58,cz_positions_left)', 'omitnan')';
        mean_left_pre=[mean_left_pre mean_left_cz_pre];
        mean_left_post=[mean_left_post mean_left_cz_post];
        powerpre=trapz(mean_left_cz_pre(:,1));
        power_left_pre=[power_left_pre powerpre];
        powerpost=trapz(mean_left_cz_post(:,1));
        power_left_post=[power_left_post powerpost];
    end
    
    %C4 LEFT
    cell_left_c4=strfind(channels_pre_left,'C4');
    c4_positions_left=[];
    for i=1:length(cell_left_c4)
        if cell2mat(cell_left_c4(i))==1
            c4_positions_left=[c4_positions_left i];
        end
    end
    if isempty(c4_positions_left)==0
        mean_left_c4_pre=mean(datos_pre_left(5:58,c4_positions_left)', 'omitnan')';
        mean_left_c4_post=mean(datos_post_left(5:58,c4_positions_left)', 'omitnan')';
        mean_left_pre=[mean_left_pre mean_left_c4_pre];
        mean_left_post=[mean_left_post mean_left_c4_post];
        powerpre=trapz(mean_left_c4_pre(:,1));
        power_left_pre=[power_left_pre powerpre];
        powerpost=trapz(mean_left_c4_post(:,1));
        power_left_post=[power_left_post powerpost];
    end

    %Figure PSD means
    figure
    if exist('mean_right_c3_post')
    plot(real_freq,mean_right_c3_post,'DisplayName',"C3")
    title("PSD MEAN OF RIGHT TRIALS POST")
    ylim([0 40]);
    xlim([0 30]);
    legend show
    hold on
    end
    if exist('mean_right_cz_post')
    plot(real_freq,mean_right_cz_post,'DisplayName',"CZ")
    legend show
    hold on
    end
    if exist('mean_right_c4_post')
    plot(real_freq,mean_right_c4_post,'DisplayName',"C4")
    legend show
    end
    saveas(gcf,name_data+"_mean_psd_right_trials_post.jpg")

    close

    figure
    if exist('mean_left_c3_post')
    plot(real_freq,mean_left_c3_post,'DisplayName',"C3")
    title("PSD MEAN OF LEFT TRIALS POST")
    ylim([0 40]);
    xlim([0 30]);
    legend show
    hold on
    end
    if exist('mean_left_cz_post')
    plot(real_freq,mean_left_cz_post,'DisplayName',"CZ")
    legend show
    hold on
    end
    if exist('mean_left_c4_post')
    plot(real_freq,mean_left_c4_post,'DisplayName',"C4")
    legend show
    end
    saveas(gcf,name_data+"_mean_psd_left_trials_post.jpg")
    close
    

     figure
    if exist('mean_right_c3_pre')
    plot(real_freq,mean_right_c3_pre,'DisplayName',"C3")
    title("PSD MEAN OF RIGHT TRIALS PRE")
    ylim([0 40]);
    xlim([0 30]);
    legend show
    hold on
    end
    if exist('mean_right_cz_pre')
    plot(real_freq,mean_right_cz_pre,'DisplayName',"CZ")
    legend show
    hold on
    end
    if exist('mean_right_c4_pre')
    plot(real_freq,mean_right_c4_pre,'DisplayName',"C4")
    legend show
    end
    saveas(gcf,name_data+"_mean_psd_right_trials_pre.jpg")

    close

    figure
    if exist('mean_left_c3_pre')
    plot(real_freq,mean_left_c3_pre,'DisplayName',"C3")
    title("PSD MEAN OF LEFT TRIALS PRE")
    ylim([0 40]);
    xlim([0 30]);
    legend show
    hold on
    end
    if exist('mean_left_cz_pre')
    plot(real_freq,mean_left_cz_pre,'DisplayName',"CZ")
    legend show
    hold on
    end
    if exist('mean_left_c4_pre')
    plot(real_freq,mean_left_c4_pre,'DisplayName',"C4")
    legend show
    end
    saveas(gcf,name_data+"_mean_psd_left_trials_pre.jpg")
    close



    %% EXCEL FOR RIGHT PSD MEANS
    %%MEAN C3%%
    
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(name_data,1),"C3", "A"+int2str(record_day+5))

    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(1),1),"C3", 'B4') %alpha
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(2),1),"C3", 'E4') %alpha peak
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(3),1),"C3", 'N4') %high beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(4),1),"C3", 'U4') %low beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(5),1),"C3", 'AB4') %beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(6),1),"C3", 'AI4') %gamma
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(7),1),"C3", 'AP4') %theta
        
    
    
    %PRE
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("PRE",1), "C3", 'B5')
    if exist('mean_right_c3_pre')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_c3_pre(:,1)==max(mean_right_c3_pre(13:30,1))));
    
        %psd_sum_alpha_rc3_pre = sum(mean_right_c3_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rc3_pre,"C3","B"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"C3","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rc3_pre = sum(mean_right_c3_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rc3_pre,"C3","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rc3_pre = sum(mean_right_c3_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rc3_pre,"C3","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rc3_pre = sum(mean_right_c3_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rc3_pre,"C3","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rc3_pre = sum(mean_right_c3_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rc3_pre,"C3","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_rc3_pre = sum(mean_right_c3_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rc3_pre = trapz(mean_right_c3_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rc3_pre,"C3","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POST",1), "C3", 'C5')
    if exist('mean_right_c3_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_c3_post(:,1)==max(mean_right_c3_post(13:30,1))));
    
        %psd_sum_alpha_rc3_post = sum(mean_right_c3_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rc3_post = trapz(mean_right_c3_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rc3_post,"C3","C"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"C3","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rc3_post = sum(mean_right_c3_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rc3_post = trapz(mean_right_c3_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rc3_post,"C3","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rc3_post = sum(mean_right_c3_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rc3_post = trapz(mean_right_c3_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rc3_post,"C3","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rc3_post = sum(mean_right_c3_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rc3_post = trapz(mean_right_c3_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rc3_post,"C3","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rc3_post = sum(mean_right_c3_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rc3_post = trapz(mean_right_c3_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rc3_post,"C3","AJ"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_rc3_post = sum(mean_right_c3_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rc3_post = trapz(mean_right_c3_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rc3_post,"C3","AQ"+int2str(record_day+5));
    
    end

    %%MEAN CZ

    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(name_data,1),"CZ", "A"+int2str(record_day+5))

    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(1),1),"CZ", 'B4') %alpha
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(2),1),"CZ", 'E4') %alpha peak
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(3),1),"CZ", 'N4') %high beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(4),1),"CZ", 'U4') %low beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(5),1),"CZ", 'AB4') %beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(6),1),"CZ", 'AI4') %gamma
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(7),1),"CZ", 'AP4') %theta


     %PRE
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("PRE",1), "CZ", 'B5')
    if exist('mean_right_cz_pre')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_cz_pre(:,1)==max(mean_right_cz_pre(13:30,1))));
    
        %psd_sum_alpha_rcz_pre = sum(mean_right_cz_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rcz_pre,"CZ","B"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"CZ","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rcz_pre = sum(mean_right_cz_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rcz_pre,"CZ","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rcz_pre = sum(mean_right_cz_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rcz_pre,"CZ","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rcz_pre = sum(mean_right_cz_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rcz_pre,"CZ","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rcz_pre = sum(mean_right_cz_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rcz_pre,"CZ","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_rcz_pre = sum(mean_right_cz_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rcz_pre = trapz(mean_right_cz_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rcz_pre,"CZ","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POST",1), "CZ", 'C5')
    if exist('mean_right_cz_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_cz_post(:,1)==max(mean_right_cz_post(13:30,1))));
    
        %psd_sum_alpha_rcz_post = sum(mean_right_cz_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rcz_post = trapz(mean_right_cz_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rcz_post,"CZ","C"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"CZ","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rcz_post = sum(mean_right_cz_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rcz_post = trapz(mean_right_cz_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rcz_post,"CZ","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rcz_post = sum(mean_right_cz_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rcz_post = trapz(mean_right_cz_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rcz_post,"CZ","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rcz_post = sum(mean_right_cz_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rcz_post = trapz(mean_right_cz_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rcz_post,"CZ","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rcz_post = sum(mean_right_cz_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rcz_post = trapz(mean_right_cz_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rcz_post,"CZ","AJ"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_rcz_post = sum(mean_right_cz_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rcz_post = trapz(mean_right_cz_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rcz_post,"CZ","AQ"+int2str(record_day+5));
    
    end


     %%MEAN C4

    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(name_data,1),"C4", "A"+int2str(record_day+5))

    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(1),1),"C4", 'B4') %alpha
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(2),1),"C4", 'E4') %alpha peak
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(3),1),"C4", 'N4') %high beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(4),1),"C4", 'U4') %low beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(5),1),"C4", 'AB4') %beta
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(6),1),"C4", 'AI4') %gamma
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell(freq_names(7),1),"C4", 'AP4') %theta




     %PRE
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("PRE",1), "C4", 'B5')
    if exist('mean_right_c4_pre')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_c4_pre(:,1)==max(mean_right_c4_pre(13:30,1))));
    
        %psd_sum_alpha_rc4_pre = sum(mean_right_c4_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rc4_pre,"C4","B"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"C4","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rc4_pre = sum(mean_right_c4_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rc4_pre,"C4","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rc4_pre = sum(mean_right_c4_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rc4_pre,"C4","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rc4_pre = sum(mean_right_c4_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rc4_pre,"C4","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rc4_pre = sum(mean_right_c4_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rc4_pre,"C4","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_rc4_pre = sum(mean_right_c4_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rc4_pre = trapz(mean_right_c4_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rc4_pre,"C4","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POST",1), "C4", 'C5')
    if exist('mean_right_c4_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_right_c4_post(:,1)==max(mean_right_c4_post(13:30,1))));
    
        %psd_sum_alpha_rc4_post = sum(mean_right_c4_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_rc4_post = trapz(mean_right_c4_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_alpha_rc4_post,"C4","C"+int2str(record_day+5));
        xlswrite("RIGHT_IT_MEAN.xls",pico_alpha,"C4","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_rc4_post = sum(mean_right_c4_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_rc4_post = trapz(mean_right_c4_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_low_beta_rc4_post,"C4","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_rc4_post = sum(mean_right_c4_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_rc4_post = trapz(mean_right_c4_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_high_beta_rc4_post,"C4","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_rc4_post = sum(mean_right_c4_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_rc4_post = trapz(mean_right_c4_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_beta_rc4_post,"C4","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_rc4_post = sum(mean_right_c4_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_rc4_post = trapz(mean_right_c4_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("RIGHT_IT_MEAN.xls",psd_int_gamma_rc4_post,"C4","AJ"+int2str(record_day+5));
    

        %Theta region (4-8 Hz)
        %psd_sum_theta_rc4_post = sum(mean_right_c4_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_rc4_post = trapz(mean_right_c4_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region

        xlswrite("RIGHT_IT_MEAN.xls",psd_int_theta_rc4_post,"C4","AQ"+int2str(record_day+5));
    
    end

    
    %% EXCEL FOR LEFT PSD MEANS

    %%MEAN C3%%
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(name_data,1),"C3", "A"+int2str(record_day+5))

    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(1),1),"C3", 'B4') %alpha
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(2),1),"C3", 'E4') %alpha peak
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(3),1),"C3", 'N4') %high beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(4),1),"C3", 'U4') %low beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(5),1),"C3", 'AB4') %beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(6),1),"C3", 'AI4') %gamma
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(7),1),"C3", 'AP4') %theta




    %PRE
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("PRE",1), "C3", 'B5')
    if exist('mean_left_c3_pre')==1
        %Alpha region _lc
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_c3_pre(:,1)==max(mean_left_c3_pre(13:30,1))));
    
        %psd_sum_alpha_lc3_pre = sum(mean_left_c3_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lc3_pre,"C3","B"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"C3","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lc3_pre = sum(mean_left_c3_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lc3_pre,"C3","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lc3_pre = sum(mean_left_c3_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lc3_pre,"C3","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lc3_pre = sum(mean_left_c3_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lc3_pre,"C3","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lc3_pre = sum(mean_left_c3_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lc3_pre,"C3","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lc3_pre = sum(mean_left_c3_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lc3_pre = trapz(mean_left_c3_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lc3_pre,"C3","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POST",1), "C3", 'C5')
    if exist('mean_left_c3_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_c3_post(:,1)==max(mean_left_c3_post(13:30,1))));
    
        %psd_sum_alpha_lc3_post = sum(mean_left_c3_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lc3_post = trapz(mean_left_c3_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lc3_post,"C3","C"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"C3","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lc3_post = sum(mean_left_c3_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lc3_post = trapz(mean_left_c3_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lc3_post,"C3","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lc3_post = sum(mean_left_c3_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lc3_post = trapz(mean_left_c3_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lc3_post,"C3","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lc3_post = sum(mean_left_c3_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lc3_post = trapz(mean_left_c3_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lc3_post,"C3","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lc3_post = sum(mean_left_c3_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lc3_post = trapz(mean_left_c3_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lc3_post,"C3","AJ"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lc3_post = sum(mean_left_c3_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lc3_post = trapz(mean_left_c3_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lc3_post,"C3","AQ"+int2str(record_day+5));
    
    end

    %%MEAN CZ%%

    
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(name_data,1),"CZ", "A"+int2str(record_day+5))

    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(1),1),"CZ", 'B4') %alpha
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(2),1),"CZ", 'E4') %alpha peak
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(3),1),"CZ", 'N4') %high beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(4),1),"CZ", 'U4') %low beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(5),1),"CZ", 'AB4') %beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(6),1),"CZ", 'AI4') %gamma
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(7),1),"CZ", 'AP4') %theta





     %PRE
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("PRE",1), "CZ", 'B5')
    if exist('mean_left_cz_pre')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_cz_pre(:,1)==max(mean_left_cz_pre(13:30,1))));
    
        %psd_sum_alpha_lcz_pre = sum(mean_left_cz_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lcz_pre,"CZ","B"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"CZ","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lcz_pre = sum(mean_left_cz_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lcz_pre,"CZ","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lcz_pre = sum(mean_left_cz_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lcz_pre,"CZ","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lcz_pre = sum(mean_left_cz_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lcz_pre,"CZ","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lcz_pre = sum(mean_left_cz_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lcz_pre,"CZ","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lcz_pre = sum(mean_left_cz_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lcz_pre = trapz(mean_left_cz_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lcz_pre,"CZ","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POST",1), "CZ", 'C5')
    if exist('mean_left_cz_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_cz_post(:,1)==max(mean_left_cz_post(13:30,1))));
    
        %psd_sum_alpha_lcz_post = sum(mean_left_cz_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lcz_post = trapz(mean_left_cz_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lcz_post,"CZ","C"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"CZ","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lcz_post = sum(mean_left_cz_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lcz_post = trapz(mean_left_cz_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lcz_post,"CZ","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lcz_post = sum(mean_left_cz_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lcz_post = trapz(mean_left_cz_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lcz_post,"CZ","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lcz_post = sum(mean_left_cz_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lcz_post = trapz(mean_left_cz_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lcz_post,"CZ","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lcz_post = sum(mean_left_cz_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lcz_post = trapz(mean_left_cz_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lcz_post,"CZ","AJ"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lcz_post = sum(mean_left_cz_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lcz_post = trapz(mean_left_cz_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lcz_post,"CZ","AQ"+int2str(record_day+5));
    
    end


     %%MEAN C4%%

    
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(name_data,1),"C4", "A"+int2str(record_day+5))

    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(1),1),"C4", 'B4') %alpha
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(2),1),"C4", 'E4') %alpha peak
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(3),1),"C4", 'N4') %high beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(4),1),"C4", 'U4') %low beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(5),1),"C4", 'AB4') %beta
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(6),1),"C4", 'AI4') %gamma
    xlswrite("LEFT_IT_MEAN.xls",mat2cell(freq_names(7),1),"C4", 'AP4') %theta






     %PRE
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("PRE",1), "C4", 'B5')

    if exist('mean_left_c4_pre')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_c4_pre(:,1)==max(mean_left_c4_pre(13:30,1))));
    
        %psd_sum_alpha_lc4_pre = sum(mean_left_c4_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lc4_pre,"C4","B"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"C4","E"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lc4_pre = sum(mean_left_c4_pre(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lc4_pre,"C4","N"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lc4_pre = sum(mean_left_c4_pre(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lc4_pre,"C4","U"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lc4_pre = sum(mean_left_c4_pre(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lc4_pre,"C4","AB"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lc4_pre = sum(mean_left_c4_pre(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lc4_pre,"C4","AI"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lc4_pre = sum(mean_left_c4_pre(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lc4_pre = trapz(mean_left_c4_pre(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lc4_pre,"C4","AP"+int2str(record_day+5));
    
    end
    %POST
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POST",1), "C4", 'C5')

    if exist('mean_left_c4_post')==1
        %Alpha region 
    
        % In the alpha region, we must first find the peak of the alpha
        % frequencies. Then, we define the region from the peak -2Hz to the
        % peak +2Hz. This is because not everyone has the same alpha region.
    
        pico_alpha=f(find(mean_left_c4_post(:,1)==max(mean_left_c4_post(13:30,1))));
    
        %psd_sum_alpha_lc4_post = sum(mean_left_c4_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %sum of psd values for delta frequency region
        psd_int_alpha_lc4_post = trapz(mean_left_c4_post(find(real_freq==pico_alpha-2):find(real_freq==pico_alpha+2),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_alpha_lc4_post,"C4","C"+int2str(record_day+5));
        xlswrite("LEFT_IT_MEAN.xls",pico_alpha,"C4","F"+int2str(record_day+5));

        %Low-beta region (13-20 Hz)
        %psd_sum_low_beta_lc4_post = sum(mean_left_c4_post(find(real_freq==13):find(real_freq==20),1)); %sum of psd values for delta frequency region
        psd_int_low_beta_lc4_post = trapz(mean_left_c4_post(find(real_freq==13):find(real_freq==20),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_low_beta_lc4_post,"C4","M"+int2str(record_day+5));
        
        %High beta region (20-30 Hz)
        %psd_sum_high_beta_lc4_post = sum(mean_left_c4_post(find(real_freq==20):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_high_beta_lc4_post = trapz(mean_left_c4_post(find(real_freq==20):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_high_beta_lc4_post,"C4","V"+int2str(record_day+5));
    
        %beta region (13-30 Hz)
        %psd_sum_beta_lc4_post = sum(mean_left_c4_post(find(real_freq==13):find(real_freq==28),1)); %sum of psd values for delta frequency region
        psd_int_beta_lc4_post = trapz(mean_left_c4_post(find(real_freq==13):find(real_freq==28),1)); %integral of psd values for delta frequency region
        
        xlswrite("LEFT_IT_MEAN.xls",psd_int_beta_lc4_post,"C4","AC"+int2str(record_day+5));
    
        %Gamma region (30-80 Hz but we use only until 40)
        %psd_sum_gamma_lc4_post = sum(mean_left_c4_post(find(real_freq==28):find(real_freq==40),1)); %sum of psd values for delta frequency region
        psd_int_gamma_lc4_post = trapz(mean_left_c4_post(find(real_freq==28):find(real_freq==40),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_gamma_lc4_post,"C4","AJ"+int2str(record_day+5));
    
        
        %Theta region (4-8 Hz)
        %psd_sum_theta_lc4_post = sum(mean_left_c4_post(find(real_freq==4):find(real_freq==8),1)); %sum of psd values for delta frequency region
        psd_int_theta_lc4_post = trapz(mean_left_c4_post(find(real_freq==4):find(real_freq==8),1)); %integral of psd values for delta frequency region
    
        xlswrite("LEFT_IT_MEAN.xls",psd_int_theta_lc4_post,"C4","AQ"+int2str(record_day+5));
    
    end

    %we write all the results the xls files. The results are divided in a
    %file with results from the LEFT trials and results from the RIGHT
    %trial.
    
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("VAS",1),"C3","H5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("VAS",1),"CZ","H5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("VAS",1),"C4","H5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER PRE",1),"C3","I5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER PRE",1),"CZ","I5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER PRE",1),"C4","I5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER POST",1),"C3","J5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER POST",1),"CZ","J5");
    xlswrite("RIGHT_IT_MEAN.xls",mat2cell("POWER POST",1),"C4","J5");

    xlswrite("RIGHT_IT_MEAN.xls",vas,"C3","H"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",vas,"CZ","H"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",vas,"C4","H"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",prerc3,"C3","I"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",prercz,"CZ","I"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",prerc4,"C4","I"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",powerc3RIGHT,"C3","J"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",powerczRIGHT,"CZ","J"+int2str(record_day+5));
    xlswrite("RIGHT_IT_MEAN.xls",powerc4RIGHT,"C4","J"+int2str(record_day+5));




    xlswrite("LEFT_IT_MEAN.xls",mat2cell("VAS",1),"C3","H5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("VAS",1),"CZ","H5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("VAS",1),"C4","H5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER PRE",1),"C3","I5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER PRE",1),"CZ","I5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER PRE",1),"C4","I5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER POST",1),"C3","J5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER POST",1),"CZ","J5");
    xlswrite("LEFT_IT_MEAN.xls",mat2cell("POWER POST",1),"C4","J5");


    xlswrite("LEFT_IT_MEAN.xls",vas,"C3","H"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",vas,"CZ","H"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",vas,"C4","H"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",prelc3,"C3","I"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",prelcz,"CZ","I"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",prelc4,"C4","I"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",powerc3LEFT,"C3","J"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",powerczLEFT,"CZ","J"+int2str(record_day+5));
    xlswrite("LEFT_IT_MEAN.xls",powerc4LEFT,"C4","J"+int2str(record_day+5));



    clearvars -except Fs f real_freq Fn resolution noverlap nfft window L Fpass left_read left_name right_read right_name
end
